personal-finance-web/config/routes.rb
PersonalFinanceWeb::Application.routes.draw do
  get "login/index"
  post "login/do_login"

  resources :categories

  resources :users

  match "login", :to => "login#index"
  match "/", :to => "login#index"

end

personal-finance-web/app/models/category.rb
class Category < ActiveRecord::Base
	belongs_to :type
	belongs_to :user
  
	def initialize(description = nil)
		super
		self.active = true
		self.description = description
	end

end

personal-finance-web/app/models/user.rb
class User < ActiveRecord::Base

  validates_presence_of :login, :name, :password, :email
  validates_size_of :login, :in => 5..12, :to_short => "Login deve ter pelo menos 5 caracteres!", :to_long => "Login deve ter no máximo 12 caracteres!"
  validates_size_of :name, :in => 5..30, :to_short => "Nome deve ter pelo menos 5 caracteres!", :to_long => "Nome deve ter no máximo 30 caracteres!"
  validates_size_of :password, :in => 5..15, :to_short => "Senha deve ter pelo menos 5 caracteres!", :to_long => "Senha deve ter no máximo 15 caracteres!"

  def initialize
    super
    self.active = true
    self.mobile_sync = false
  end

end

personal-finance-web/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :set_locale

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

end

personal-finance-web/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.xml
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.xml
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.xml
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.xml
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to(@category, :notice => 'Categoria criada com sucesso.') }
        format.xml  { render :xml => @category, :status => :created, :location => @category }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.xml
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to(@category, :notice => 'Categoria atualizada com sucesso.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.xml
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to(categories_url) }
      format.xml  { head :ok }
    end
  end
end

personal-finance-web/app/controllers/login_controller.rb
class LoginController < ApplicationController
  def index
  end

  def do_login
  end

  def logout
  end

end

personal-finance-web/app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.xml
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end

  # GET /users/1
  # GET /users/1.xml
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/new
  # GET /users/new.xml
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.xml
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to(@user, :notice => 'Usuário criado com sucesso.') }
        format.xml  { render :xml => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.xml
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(@user, :notice => 'Usuário atualizado com sucesso.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end
end

personal-finance-web/app/helpers/application_helper.rb
module ApplicationHelper
end

personal-finance-web/app/helpers/categories_helper.rb
module CategoriesHelper
end

personal-finance-web/app/helpers/login_helper.rb
module LoginHelper
end

personal-finance-web/app/helpers/users_helper.rb
module UsersHelper
end

personal-finance-web/app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :type %><br />
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </div>
  <div class="field">
    <%= f.label :active %><br />
    <%= f.check_box :active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

personal-finance-web/app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

personal-finance-web/app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <tr>
    <th>Description</th>
    <th>Type</th>
    <th>User</th>
    <th>Active</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= category.description %></td>
    <td><%= category.type %></td>
    <td><%= category.user %></td>
    <td><%= category.active %></td>
    <td><%= link_to 'Show', category %></td>
    <td><%= link_to 'Edit', edit_category_path(category) %></td>
    <td><%= link_to 'Destroy', category, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Category', new_category_path %>

personal-finance-web/app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

personal-finance-web/app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Description:</b>
  <%= @category.description %>
</p>

<p>
  <b>Type:</b>
  <%= @category.type %>
</p>

<p>
  <b>User:</b>
  <%= @category.user %>
</p>

<p>
  <b>Active:</b>
  <%= @category.active %>
</p>


<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

personal-finance-web/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= t :project_name  %></title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

personal-finance-web/app/views/login/index.html.erb
<%form_tag :action => :do_login do %>

  <table id="login">
    <tr>
      <td><%= t(:user_login) %></td>
      <td><input type="text" name="user_login"/></td>
    </tr>
    <tr>
      <td><%= t(:user_password) %></td>
      <td><input type="password" name="user_password"/></td>
    </tr>
  </table>

<% end %>

personal-finance-web/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label t :user_login %><br />
    <%= f.text_field :login, :maxlength => 12 %>
  </div>
  <div class="field">
    <%= f.label t :user_name %><br />
    <%= f.text_field :name, :maxlength => 30 %>
  </div>
  <div class="field">
    <%= f.label t :user_password %><br />
    <%= f.password_field :password, :maxlength => 15 %>
  </div>
  <div class="field">
    <%= f.label t :user_email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label t :user_active %><br />
    <%= f.check_box :active %>
  </div>

  <div class="actions">
    <%= f.submit t :save %>
  </div>
<% end %>

personal-finance-web/app/views/users/edit.html.erb
<h1>Editando usuário</h1>

<%= render 'form' %>

<%= link_to t :show, @user %> |
<%= link_to t :back, users_path %>

personal-finance-web/app/views/users/index.html.erb
<h1><%= (t :users) %></h1>

<table>
  <tr>
    <th><%= t :user_login %></th>
    <th><%= t :user_name %></th>
    <th><%= t :user_password %></th>
    <th><%= t :user_email %></th>
    <th><%= t :user_active %></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.login %></td>
    <td><%= user.name %></td>
    <td><%= user.password %></td>
    <td><%= user.email %></td>
    <td><%= user.active %></td>
    <td><%= link_to t(:show), user %></td>
    <td><%= link_to t(:edit), edit_user_path(user) %></td>
    <td><%= link_to t(:delete), user, :confirm => 'Deseja mesmo deletar?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to t(:users_new), new_user_path %>

personal-finance-web/app/views/users/new.html.erb
<h1>Novo usuário</h1>

<%= render 'form' %>

<%= link_to t(:back), users_path %>

personal-finance-web/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
<b><%= t :user_login%></b>
  <%= @user.login %>
</p>

<p>
<b><%= t :user_name %></b>
  <%= @user.name %>
</p>

<p>
<b><%= t :user_password %></b>
  <%= @user.password %>
</p>

<p>
<b><%= t :user_email %></b>
  <%= @user.email %>
</p>

<p>
<b><%= t :user_active %></b>
  <%= @user.active %>
</p>

<%= link_to t :edit, edit_user_path(@user) %> |
<%= link_to t :back, users_path %>